name: deploy 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos high sierra 10.13.6
    steps:
      - uses: action/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18.2'
      - name: Build web-app
        run: |
        npm ci 
        npm run build
      - name: Deploy to gh-pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_dir: ./build